@startuml
'https://plantuml.com/ie-diagram

entity "order_items" as ori {
 * PK: id: varchar
 --
 * quantity: int
 * price: bigint
 * product_id: varchar
 --
 * FK order_id: varchar
}

entity "orders" as or {
 * PK: id: varchar
 --
 * created_at: timestamp <<generated>>
 * total: bigint
 * status: varchar
}

ori }|--|| or

@enduml