@startuml
'https://plantuml.com/class-diagram

interface GetProductUseCase
class GetSingleProduct
class GetProducts
class GetProductBy

GetProductUseCase <|-- GetSingleProduct
GetProductUseCase <|-- GetProducts
GetProductUseCase <|-- GetProductBy

interface GetProductPort
note left: Defines all needed methods for getting product\nCould be complex methods that involves a few step\nFor example, FindById + Mapping to Domain Dto
class GetProductPersistentAdapter
note left: Implements all methods for getting product from db\nUtilizes needed Repositories
interface ProductReactiveRepository
note top: Defines and Implements CRUD methods\nFor example, findByName, findByIdEqualsIgnoreCaseAndContains

GetProductPort <|-- GetProductPersistentAdapter
GetProductPersistentAdapter *- ProductReactiveRepository

GetSingleProduct *-- GetProductPort
GetProducts *-- GetProductPort
GetProductBy *-- GetProductPort

interface GetProductUseCase<ID> {
    + Flux<GetProductResponse> getProduct(ID identifier)
    + String case()
}

class GetSingleProduct {
    - GetProductPort getProductPort
}

class GetProducts {
    - GetProductPort getProductPort
}

class GetProductBy {
    - GetProductPort getProductPort
}

class GetProductPersistentAdapter {
    - ProductReactiveRepository productReactiveRepository
}

@enduml