name: Sample workflow

env:
  PLATFORM_DIRECTORY: ./3-platform
  PROJECT_ORDER: ${{ env.PLATFORM_DIRECTORY }}/order

on: [push, pull_request]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: ${{ env.PROJECT_ORDER }}